name: animated_scroll_item
description: Wrapper for items inside lists or scrollable views that allows you to customize scroll animation
version: 0.0.1
homepage: https://github.com/G33kFreak/animated-scroll-item
repository: https://github.com/G33kFreak/animated-scroll-item

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
